import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  //Make sure to have backticks for this template
  template: `
  <p> This is the update for the information</p>
  <!-- Need to read up on #ElementRef-->
  <input #inputElementRef
  [value]="title"
  (keyup.enter)="changeTitle(inputElementRef)">

<button (click)="changeTitle(inputElementRef)">
Save
</button>


  <hr>

  <p>
    input-button-unit works!
    this is the title {{title}}
    </p>
  `,
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
  title = 'Hello World, BAD ASS';
  constructor() {
    this.title = 'I Love Angular, actually I love programming.';
//Methods are outside of constructor still
  }

  changeTitle(inputElementReference) {
    console.log(inputElementReference);
    this.title = inputElementReference.value;
  }





//binding information in another way
  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  ngOnInit() {
    //sets a time out for the change of info
    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);

    // Methods >> this.changeTitle is implemented here from building in the constructor earlier

  }

}
