import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  //Make sure to have backticks for this template
  template: `
    <p>
      input-button-unit works!
    this is the title {{title}}
    </p>
    <!-- <input value="Hello Coffee!"> -->
    <input [value]="title"> <!-- this puts the title inside of the input -->
    <hr>
    <input [value]="generateTitle()">

    {{ generateTitle() }}
    <button>Save</button>
  `,
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {
  title = 'Hello World, BAD ASS';
  constructor() {
    this.title = 'I Love Angular, actually I love programming.';
//Methods are outside of constructor still
  }

  changeTitle(newTitle: string) {
    console.log(newTitle);
    this.title = newTitle;
    console.log(newTitle);

  }
//binding information in another way
  generateTitle(): string {
    return 'This title was generated by a method.';
  }

  ngOnInit() {
    //sets a time out for the change of info
    setTimeout(() => {
      this.title = 'This is not the title you are looking for';
    }, 3000);

    this.title = 'Angular CLI Rules! Yeah sure okay';
    console.log(this.title);
    this.changeTitle('My First Angular App');
    // Methods >> this.changeTitle is implemented here from building in the constructor earlier

  }

}
